### ISSUE TITLE
Migrate to ECS

### ISSUE THREAD

**Issue by dtan4** [dtan4/paus#19]
## WHY

Currently Paus runs on Docker Swarm cluster + etcd. I had tested and evaluated Paus cluster at our development/staging environments, and then I found there are some difficulties to maintain Swarm cluster.
### Pros of Swarm + etcd
- Run on local machine as well as cloud
- Easy to implement 
- Docker Registry is not necessary
### Cons
- Difficult to get container/service logs
- Difficult to delete launching services
- Difficult to scale machines/containers
- Sometimes swarm Docker daemon hangs up
- Executing `docker-compose` command is required
## WHAT

Migrate backend to AWS ECS. With ECS, most operations will be conducted easily.
### Pros of ECS
- Easy to get container/service logs via CloudWatch Logs
- Easy to scale machines/containers by AutoScaling + CloudWatch Metrics
- Be able to manage services via API
- `docker-compose` command is no more required
### Cons of ECS
- Cannot run on local machine
- Ops engineer have to set up ECS cluster at first
- Some external Docker Registry is required
## TODO
- [x] Push images built on Paus to ECR
- Deploy
  - [x] Create TaskDefinition
  - [x] Create Service
  - [ ] Register Service to reverse proxy
- [x] Change Datastore from etcd to DynamoDB
- [ ] Change dashboard backend to ECS + DynamoDB
